---
title: "Example Pretty XTable"
author: "Keaton Stagaman"
date: "July 7, 2016"
output: 
    pdf_document:
        includes:
            in_header: header2.tex
        keep_tex: true
---

## Load libraries and source files

```{r libraries_and_sources, message=FALSE}
library(ggplot2)
source("xtable_summary.R", chdir=TRUE)
```

## Data plot with regression line

```{r cars_plot, fig.width=6, fig.heigh=3.5, fig.cap="Car distance by speed with regression line"}
ggplot(cars, aes(x=speed, y=dist)) + 
    geom_point() + 
    stat_smooth(method="lm") + 
    labs(x="Speed", y="Distance")
```


## Linear model calculation

```{r car_lm}
cars.lm <- lm(dist ~ speed, data=cars)
xtable.summary(model.obj=cars.lm, file.id="cars", alt.factor.names=c("Speed"))
```

\begin{table}[h!]
\captionsetup[subtable]{labelformat=empty}
\centering
\subfloat[]{\label{tab:cars_lm-a}{\input{cars_lm_factors}}}\quad
\subfloat[]{\label{tab:cars_lm-b}{\input{cars_lm_rsqP}}}
\caption{Linear model for distance by speed}
\label{tab:cars_lm}
\end{table}
